using Core.Domain;

namespace Core.Application.MasterData;

public sealed record DepartmentResponse(
    Guid Id,
    string Name,
    CalculationProfile CalculationType,
    decimal GoalBonusPercentage,
    decimal LowRevenueThreshold,
    decimal LowRevenueBonusPct,
    string? Description,
    bool IsActive,
    bool IsAllocatedFixed,
    bool RoutesFixedToLimaKarttos);

public sealed record CreateDepartmentRequest(
    string Name,
    CalculationProfile CalculationType,
    decimal GoalBonusPercentage,
    decimal LowRevenueThreshold,
    decimal LowRevenueBonusPct,
    string? Description,
    bool IsActive,
    bool IsAllocatedFixed,
    bool RoutesFixedToLimaKarttos);

public sealed record UpdateDepartmentRequest(
    string Name,
    CalculationProfile CalculationType,
    decimal GoalBonusPercentage,
    decimal LowRevenueThreshold,
    decimal LowRevenueBonusPct,
    string? Description,
    bool IsActive,
    bool IsAllocatedFixed,
    bool RoutesFixedToLimaKarttos);

public sealed record CareerLevelResponse(
    Guid Id,
    string Name,
    Guid? DepartmentId,
    CalculationProfile Profile,
    bool IsActive,
    decimal BaseSalary,
    decimal CommissionWithoutGoalPct,
    decimal CommissionWithGoalPct,
    decimal CommissionWithSuperGoalPct,
    decimal GroupCommissionPerPercent,
    decimal GroupCommissionPer20Percent,
    decimal DefaultCpaValue,
    decimal GoalBonusValue,
    decimal FtdRateBase,
    decimal FtdRateWithGoal,
    decimal FtdRateWithSuperGoal,
    decimal FtdSuperbetRate,
    int FtdBonusEvery,
    decimal FtdBonusValue,
    decimal SalesPctBase,
    decimal SalesPctWithGoal,
    decimal SalesPctWithSuperGoal,
    decimal SalesBonusEvery,
    decimal SalesBonusValue,
    decimal RevPct,
    decimal BetanoInternaValue,
    decimal BetanoMundoBetValue,
    decimal SupFtdSuperbetNoGoal,
    decimal SupFtdSuperbetWithGoal,
    decimal SupFtdOtherNoGoal,
    decimal SupFtdOtherWithGoal,
    decimal SupSalesPctNoGoal,
    decimal SupSalesPctWithGoal,
    decimal SupRevPct,
    decimal NetRevenueFactor,
    decimal NetRevenuePctNoGoal,
    decimal NetRevenuePctWithGoal,
    decimal TrafficInvestmentCommissionPct,
    decimal TrafficCpaEsportiva,
    decimal TrafficCpaStake,
    decimal TrafficCpaBetano,
    decimal TrafficCpaBetMgm,
    decimal TrafficCpaNovibet,
    decimal TrafficCpaBetFair,
    decimal TrafficCpaBlaze,
    decimal TrafficCpaSuperbet,
    decimal TrafficCpaHiperbet,
    decimal TrafficSupBonus,
    decimal TrafficSupCommissionPct);

public sealed record CreateCareerLevelRequest(
    string Name,
    Guid? DepartmentId,
    CalculationProfile Profile,
    bool IsActive,
    decimal BaseSalary,
    decimal CommissionWithoutGoalPct,
    decimal CommissionWithGoalPct,
    decimal CommissionWithSuperGoalPct,
    decimal GroupCommissionPerPercent,
    decimal GroupCommissionPer20Percent,
    decimal DefaultCpaValue,
    decimal GoalBonusValue,
    decimal FtdRateBase,
    decimal FtdRateWithGoal,
    decimal FtdRateWithSuperGoal,
    decimal FtdSuperbetRate,
    int FtdBonusEvery,
    decimal FtdBonusValue,
    decimal SalesPctBase,
    decimal SalesPctWithGoal,
    decimal SalesPctWithSuperGoal,
    decimal SalesBonusEvery,
    decimal SalesBonusValue,
    decimal RevPct,
    decimal BetanoInternaValue,
    decimal BetanoMundoBetValue,
    decimal SupFtdSuperbetNoGoal,
    decimal SupFtdSuperbetWithGoal,
    decimal SupFtdOtherNoGoal,
    decimal SupFtdOtherWithGoal,
    decimal SupSalesPctNoGoal,
    decimal SupSalesPctWithGoal,
    decimal SupRevPct,
    decimal NetRevenueFactor,
    decimal NetRevenuePctNoGoal,
    decimal NetRevenuePctWithGoal,
    decimal TrafficInvestmentCommissionPct,
    decimal TrafficCpaEsportiva,
    decimal TrafficCpaStake,
    decimal TrafficCpaBetano,
    decimal TrafficCpaBetMgm,
    decimal TrafficCpaNovibet,
    decimal TrafficCpaBetFair,
    decimal TrafficCpaBlaze,
    decimal TrafficCpaSuperbet,
    decimal TrafficCpaHiperbet,
    decimal TrafficSupBonus,
    decimal TrafficSupCommissionPct);

public sealed record UpdateCareerLevelRequest(
    string Name,
    Guid? DepartmentId,
    CalculationProfile Profile,
    bool IsActive,
    decimal BaseSalary,
    decimal CommissionWithoutGoalPct,
    decimal CommissionWithGoalPct,
    decimal CommissionWithSuperGoalPct,
    decimal GroupCommissionPerPercent,
    decimal GroupCommissionPer20Percent,
    decimal DefaultCpaValue,
    decimal GoalBonusValue,
    decimal FtdRateBase,
    decimal FtdRateWithGoal,
    decimal FtdRateWithSuperGoal,
    decimal FtdSuperbetRate,
    int FtdBonusEvery,
    decimal FtdBonusValue,
    decimal SalesPctBase,
    decimal SalesPctWithGoal,
    decimal SalesPctWithSuperGoal,
    decimal SalesBonusEvery,
    decimal SalesBonusValue,
    decimal RevPct,
    decimal BetanoInternaValue,
    decimal BetanoMundoBetValue,
    decimal SupFtdSuperbetNoGoal,
    decimal SupFtdSuperbetWithGoal,
    decimal SupFtdOtherNoGoal,
    decimal SupFtdOtherWithGoal,
    decimal SupSalesPctNoGoal,
    decimal SupSalesPctWithGoal,
    decimal SupRevPct,
    decimal NetRevenueFactor,
    decimal NetRevenuePctNoGoal,
    decimal NetRevenuePctWithGoal,
    decimal TrafficInvestmentCommissionPct,
    decimal TrafficCpaEsportiva,
    decimal TrafficCpaStake,
    decimal TrafficCpaBetano,
    decimal TrafficCpaBetMgm,
    decimal TrafficCpaNovibet,
    decimal TrafficCpaBetFair,
    decimal TrafficCpaBlaze,
    decimal TrafficCpaSuperbet,
    decimal TrafficCpaHiperbet,
    decimal TrafficSupBonus,
    decimal TrafficSupCommissionPct);

public sealed record ProjectResponse(
    Guid Id,
    string Name,
    string? Client,
    ProjectPlatform Platform,
    bool IsActive,
    bool IsDefaultAllocationTarget,
    bool ExcludesGoalBonus,
    bool ExcludesSupervisorFixedAllocation);

public sealed record CreateProjectRequest(
    string Name,
    string? Client,
    ProjectPlatform Platform,
    bool IsActive,
    bool IsDefaultAllocationTarget,
    bool ExcludesGoalBonus,
    bool ExcludesSupervisorFixedAllocation);

public sealed record UpdateProjectRequest(
    string Name,
    string? Client,
    ProjectPlatform Platform,
    bool IsActive,
    bool IsDefaultAllocationTarget,
    bool ExcludesGoalBonus,
    bool ExcludesSupervisorFixedAllocation);

public sealed record PaymentMethodResponse(
    Guid Id,
    string Name,
    bool IsActive);

public sealed record CreatePaymentMethodRequest(
    string Name,
    bool IsActive);

public sealed record UpdatePaymentMethodRequest(
    string Name,
    bool IsActive);
