namespace WebApp.Blazor.Services;

public enum CareerLevelApiStatus
{
    Success,
    ValidationError,
    NotFound,
    Conflict,
    Forbidden,
    Error
}

public sealed record CareerLevelDto(
    Guid Id,
    string Name,
    Guid? DepartmentId,
    CalculationProfile Profile,
    bool IsActive,
    decimal BaseSalary,
    decimal CommissionWithoutGoalPct,
    decimal CommissionWithGoalPct,
    decimal CommissionWithSuperGoalPct,
    decimal GroupCommissionPerPercent,
    decimal GroupCommissionPer20Percent,
    decimal DefaultCpaValue,
    decimal GoalBonusValue,
    decimal FtdRateBase,
    decimal FtdRateWithGoal,
    decimal FtdRateWithSuperGoal,
    decimal FtdSuperbetRate,
    int FtdBonusEvery,
    decimal FtdBonusValue,
    decimal SalesPctBase,
    decimal SalesPctWithGoal,
    decimal SalesPctWithSuperGoal,
    decimal SalesBonusEvery,
    decimal SalesBonusValue,
    decimal RevPct,
    decimal BetanoInternaValue,
    decimal BetanoMundoBetValue,
    decimal SupFtdSuperbetNoGoal,
    decimal SupFtdSuperbetWithGoal,
    decimal SupFtdOtherNoGoal,
    decimal SupFtdOtherWithGoal,
    decimal SupSalesPctNoGoal,
    decimal SupSalesPctWithGoal,
    decimal SupRevPct,
    decimal NetRevenueFactor,
    decimal NetRevenuePctNoGoal,
    decimal NetRevenuePctWithGoal,
    decimal TrafficInvestmentCommissionPct,
    decimal TrafficCpaEsportiva,
    decimal TrafficCpaStake,
    decimal TrafficCpaBetano,
    decimal TrafficCpaBetMgm,
    decimal TrafficCpaNovibet,
    decimal TrafficCpaBetFair,
    decimal TrafficCpaBlaze,
    decimal TrafficCpaSuperbet,
    decimal TrafficCpaHiperbet,
    decimal TrafficSupBonus,
    decimal TrafficSupCommissionPct);

public sealed record CareerLevelRequest(
    string Name,
    Guid? DepartmentId,
    CalculationProfile Profile,
    bool IsActive,
    decimal BaseSalary,
    decimal CommissionWithoutGoalPct,
    decimal CommissionWithGoalPct,
    decimal CommissionWithSuperGoalPct,
    decimal GroupCommissionPerPercent,
    decimal GroupCommissionPer20Percent,
    decimal DefaultCpaValue,
    decimal GoalBonusValue,
    decimal FtdRateBase,
    decimal FtdRateWithGoal,
    decimal FtdRateWithSuperGoal,
    decimal FtdSuperbetRate,
    int FtdBonusEvery,
    decimal FtdBonusValue,
    decimal SalesPctBase,
    decimal SalesPctWithGoal,
    decimal SalesPctWithSuperGoal,
    decimal SalesBonusEvery,
    decimal SalesBonusValue,
    decimal RevPct,
    decimal BetanoInternaValue,
    decimal BetanoMundoBetValue,
    decimal SupFtdSuperbetNoGoal,
    decimal SupFtdSuperbetWithGoal,
    decimal SupFtdOtherNoGoal,
    decimal SupFtdOtherWithGoal,
    decimal SupSalesPctNoGoal,
    decimal SupSalesPctWithGoal,
    decimal SupRevPct,
    decimal NetRevenueFactor,
    decimal NetRevenuePctNoGoal,
    decimal NetRevenuePctWithGoal,
    decimal TrafficInvestmentCommissionPct,
    decimal TrafficCpaEsportiva,
    decimal TrafficCpaStake,
    decimal TrafficCpaBetano,
    decimal TrafficCpaBetMgm,
    decimal TrafficCpaNovibet,
    decimal TrafficCpaBetFair,
    decimal TrafficCpaBlaze,
    decimal TrafficCpaSuperbet,
    decimal TrafficCpaHiperbet,
    decimal TrafficSupBonus,
    decimal TrafficSupCommissionPct);

public sealed record CareerLevelListResult(
    CareerLevelApiStatus Status,
    IReadOnlyList<CareerLevelDto>? CareerLevels = null,
    string? ErrorCode = null,
    string? Message = null);

public sealed record CareerLevelMutationResult(
    CareerLevelApiStatus Status,
    CareerLevelDto? CareerLevel = null,
    string? ErrorCode = null,
    string? Message = null);
